### ISSUE TITLE
A JavaScript clock.

### ISSUE THREAD

**Issue by surbhi400** [Yashika1410/HacktoberFest-2022#22]
I want to create a JavaScript clock which shows current time. 
@Yashika1410  please assign me this issue under hactoberfest.

![clock](https://user-images.githubusercontent.com/77582783/193512435-2a5a17de-19a3-4bd0-a6bd-d063e8e52895.png)

**Comment by dysonenvil** [comment]
please assign me.

**Comment by Yashika1410** [comment]
@surbhi400 are you creating this clock or should i assign it to @dysonenvil

**Comment by Yashika1410** [comment]
@surbhi400 ok no issues i just want to confirm it.

**Comment by surbhi400** [comment]
@Yashika1410 Can you please add hactoberfest label to this issue.
